In [20]:
# Importing required module

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
# importing the dataset
df = pd.read_csv('covid_19_Dataset.csv')

df

          DATE    country    NEW Cases  NEW_DEATHS vaccinated
0    2024-11-01  Argentina         NaN         NaN     unknown
1    2024-11-01  Australia         0.0         0.0         327
2    2024-11-01  Australia         0.0         0.0         327
3    2024-11-01     Brazil       971.0        48.0         430
4    2024-11-01     Canada       176.0         8.0     unknown
..          ...        ...         ...         ...         ...
160  2024-11-30     Brazil       514.0        25.0     unknown
161  2024-11-30     Canada      1133.0        56.0         438
162  2024-11-30     Canada      1133.0        56.0         438
163  2024-11-30      China         0.0         0.0     unknown
164  2024-11-30      China         0.0         0.0     unknown

[165 rows x 5 columns]

In [43]:
# checking the data information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE         165 non-null    object
 1   country      165 non-null    object
 2    NEW Cases   154 non-null    float64
 3   new_deaths   139 non-null    float64
 4   vaccinated   165 non-null    object
dtypes: float64(2), object(3)
memory usage: 6.6+ KB

In [44]:
# checking the data information

df.shape

(165, 5)

In [46]:
# Renaming coumns
df.rename(columns={'NEW Cases': 'new_cases', 'NEW_DEATHS': 'new_deaths', 'DATE': 'date'}, inplace=True)

df

          DATE    country    NEW Cases  new_deaths vaccinated
0    2024-11-01  Argentina         NaN         NaN     unknown
1    2024-11-01  Australia         0.0         0.0         327
2    2024-11-01  Australia         0.0         0.0         327
3    2024-11-01     Brazil       971.0        48.0         430
4    2024-11-01     Canada       176.0         8.0     unknown
..          ...        ...         ...         ...         ...
160  2024-11-30     Brazil       514.0        25.0     unknown
161  2024-11-30     Canada      1133.0        56.0         438
162  2024-11-30     Canada      1133.0        56.0         438
163  2024-11-30      China         0.0         0.0     unknown
164  2024-11-30      China         0.0         0.0     unknown

[165 rows x 5 columns]

In [47]:
# Strip leading and trailing spaces from column names
df.columns = df.columns.str.strip().str.lower()

df

           date    country  new cases  new_deaths vaccinated
0    2024-11-01  Argentina        NaN         NaN    unknown
1    2024-11-01  Australia        0.0         0.0        327
2    2024-11-01  Australia        0.0         0.0        327
3    2024-11-01     Brazil      971.0        48.0        430
4    2024-11-01     Canada      176.0         8.0    unknown
..          ...        ...        ...         ...        ...
160  2024-11-30     Brazil      514.0        25.0    unknown
161  2024-11-30     Canada     1133.0        56.0        438
162  2024-11-30     Canada     1133.0        56.0        438
163  2024-11-30      China        0.0         0.0    unknown
164  2024-11-30      China        0.0         0.0    unknown

[165 rows x 5 columns]

In [48]:
# Renaming coumns again


df.rename(columns={'new cases': 'new_cases'}, inplace=True)

df

           date    country  new_cases  new_deaths vaccinated
0    2024-11-01  Argentina        NaN         NaN    unknown
1    2024-11-01  Australia        0.0         0.0        327
2    2024-11-01  Australia        0.0         0.0        327
3    2024-11-01     Brazil      971.0        48.0        430
4    2024-11-01     Canada      176.0         8.0    unknown
..          ...        ...        ...         ...        ...
160  2024-11-30     Brazil      514.0        25.0    unknown
161  2024-11-30     Canada     1133.0        56.0        438
162  2024-11-30     Canada     1133.0        56.0        438
163  2024-11-30      China        0.0         0.0    unknown
164  2024-11-30      China        0.0         0.0    unknown

[165 rows x 5 columns]

In [49]:
# Converting Date column data type

df['date'] = pd.to_datetime(df['date'], format='mixed', dayfirst=True)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        165 non-null    datetime64[ns]
 1   country     165 non-null    object
 2   new_cases   154 non-null    float64
 3   new_deaths  139 non-null    float64
 4   vaccinated  165 non-null    object
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 6.6+ KB

In [50]:
# viewing data

df

          date    country  new_cases  new_deaths vaccinated
0   2024-11-01  Argentina        NaN         NaN    unknown
1   2024-11-01  Australia        0.0         0.0        327
2   2024-11-01  Australia        0.0         0.0        327
3   2024-11-01     Brazil      971.0        48.0        430
4   2024-11-01     Canada      176.0         8.0    unknown
..         ...        ...        ...         ...        ...
160 2024-11-30     Brazil      514.0        25.0    unknown
161 2024-11-30     Canada     1133.0        56.0        438
162 2024-11-30     Canada     1133.0        56.0        438
163 2024-11-30      China        0.0         0.0    unknown
164 2024-11-30      China        0.0         0.0    unknown

[165 rows x 5 columns]

In [51]:
# Checking columns with null values

df.isnull().sum()

date           0
country        0
new_cases     11
new_deaths    26
vaccinated     0
dtype: int64

In [52]:
# viewing rows with null values

df[df.isnull().any(axis=1)]

          date    country  new_cases  new_deaths vaccinated
0   2024-11-01  Argentina        NaN         NaN    unknown
7   2024-11-02  Australia        0.0         NaN        336
12  2024-11-03  Australia        NaN         NaN        474
13  2024-11-03     Brazil      641.0         NaN         47
22  2024-11-05  Argentina      283.0         NaN         41
30  2024-11-06     Canada      152.0         NaN        421
40  2024-11-08     Brazil      212.0         NaN        313
55  2024-11-11     Brazil        NaN         NaN        285
59  2024-11-12  Australia      796.0         NaN        433
60  2024-11-12     Brazil        NaN         NaN        182
64  2024-11-13  Australia      783.0         NaN        436
76  2024-11-15     Brazil        NaN         NaN    unknown
85  2024-11-17  Argentina      759.0         NaN        397
86  2024-11-17  Argentina      759.0         NaN        397
92  2024-11-18  Argentina        NaN         NaN    unknown
93  2024-11-18  Australia      882.0         NaN        458
102 2024-11-19      China        NaN         NaN        169
108 2024-11-20     Canada        NaN         NaN        332
109 2024-11-20      China      116.0         NaN    unknown
115 2024-11-22  Argentina      896.0         NaN        349
130 2024-11-24     Canada      597.0         NaN        319
133 2024-11-25  Australia        NaN         NaN        353
143 2024-11-27  Australia     1074.0         NaN        446
145 2024-11-27     Canada        NaN         NaN        499
150 2024-11-28     Canada      803.0         NaN        483
155 2024-11-29     Brazil        NaN         NaN         62

In [55]:
# Dropping rows with too much unknown or NaN

df.drop(index=[0,7,12,55,60,76,92,102,108,109,133,145,155], inplace=True)

In [57]:
# viewing rows with null values again


df[df.isnull().any(axis=1)]

          date    country  new_cases  new_deaths vaccinated
13  2024-11-03     Brazil      641.0         NaN         47
22  2024-11-05  Argentina      283.0         NaN         41
30  2024-11-06     Canada      152.0         NaN        421
40  2024-11-08     Brazil      212.0         NaN        313
59  2024-11-12  Australia      796.0         NaN        433
64  2024-11-13  Australia      783.0         NaN        436
85  2024-11-17  Argentina      759.0         NaN        397
86  2024-11-17  Argentina      759.0         NaN        397
93  2024-11-18  Australia      882.0         NaN        458
115 2024-11-22  Argentina      896.0         NaN        349
130 2024-11-24     Canada      597.0         NaN        319
143 2024-11-27  Australia     1074.0         NaN        446
150 2024-11-28     Canada      803.0         NaN        483

In [64]:
# Checking for duplicate

df[df.duplicated(keep=False)]

          date    country  new_cases  new_deaths vaccinated
1   2024-11-01  Australia        0.0         0.0        327
2   2024-11-01  Australia        0.0         0.0        327
18  2024-11-04     Brazil      793.0        39.0        137
19  2024-11-04     Brazil      793.0        39.0        137
38  2024-11-08  Australia      313.0        15.0        486
39  2024-11-08  Australia      313.0        15.0        486
68  2024-11-14  Argentina      806.0        40.0         11
69  2024-11-14  Argentina      806.0        40.0         11
83  2024-11-16      China      727.0        36.0        326
84  2024-11-16      China      727.0        36.0        326
85  2024-11-17  Argentina      759.0         NaN        397
86  2024-11-17  Argentina      759.0         NaN        397
88  2024-11-17     Brazil       18.0         0.0         37
89  2024-11-17     Brazil       18.0         0.0         37
96  2024-11-18      China       94.0         4.0        138
97  2024-11-18      China       94.0         4.0        138
103 2024-11-20  Argentina      589.0        29.0        120
104 2024-11-20  Argentina      589.0        29.0        120
106 2024-11-20     Brazil      587.0        29.0         11
107 2024-11-20     Brazil      587.0        29.0         11
117 2024-11-22     Brazil      345.0        17.0        397
118 2024-11-22     Brazil      345.0        17.0        397
122 2024-11-23  Australia     1087.0        54.0        395
123 2024-11-23  Australia     1087.0        54.0        395
151 2024-11-28      China      401.0        20.0        190
152 2024-11-28      China      401.0        20.0        190
161 2024-11-30     Canada     1133.0        56.0        438
162 2024-11-30     Canada     1133.0        56.0        438
163 2024-11-30      China        0.0         0.0    unknown
164 2024-11-30      China        0.0         0.0    unknown

In [65]:
# Dropping duplicate

df.drop_duplicates(inplace=True)

In [66]:
# confirming if duplicates have been removed

df[df.duplicated()]

Empty DataFrame
Columns: [date, country, new_cases, new_deaths, vaccinated]
Index: []

In [67]:
# viewing rows with null values again


df[df.isnull().any(axis=1)]

          date    country  new_cases  new_deaths vaccinated
13  2024-11-03     Brazil      641.0         NaN         47
22  2024-11-05  Argentina      283.0         NaN         41
30  2024-11-06     Canada      152.0         NaN        421
40  2024-11-08     Brazil      212.0         NaN        313
59  2024-11-12  Australia      796.0         NaN        433
64  2024-11-13  Australia      783.0         NaN        436
85  2024-11-17  Argentina      759.0         NaN        397
93  2024-11-18  Australia      882.0         NaN        458
115 2024-11-22  Argentina      896.0         NaN        349
130 2024-11-24     Canada      597.0         NaN        319
143 2024-11-27  Australia     1074.0         NaN        446
150 2024-11-28     Canada      803.0         NaN        483

In [69]:
df.head(20)

         date    country  new_cases  new_deaths vaccinated
1  2024-11-01  Australia        0.0         0.0        327
3  2024-11-01     Brazil      971.0        48.0        430
4  2024-11-01     Canada      176.0         8.0    unknown
5  2024-11-01      China     1034.0        51.0        462
6  2024-11-02  Argentina       23.0         1.0        195
8  2024-11-02     Brazil      185.0         9.0        173
9  2024-11-02     Canada      615.0        30.0        369
10 2024-11-02      China      376.0        18.0         61
11 2024-11-03  Argentina      337.0        16.0        425
13 2024-11-03     Brazil      641.0         NaN         47
14 2024-11-03     Canada      785.0        39.0        320
15 2024-11-03      China       35.0         1.0        369
16 2024-11-04  Argentina       96.0         4.0        383
17 2024-11-04  Australia        0.0         0.0        440
18 2024-11-04     Brazil      793.0        39.0        137
20 2024-11-04     Canada      884.0        44.0        493
21 2024-11-04      China      696.0        34.0    unknown
22 2024-11-05  Argentina      283.0         NaN         41
23 2024-11-05  Australia      140.0         7.0        450
24 2024-11-05     Brazil      638.0        31.0        346

In [ ]:
# checking columns with unknown values

df[df['vaccinated'] == 'unknown']

          date country  new_cases  new_deaths vaccinated
4   2024-11-01  Brazil      176.0         8.0    unknown
21  2024-11-04  Brazil      696.0        34.0    unknown
37  2024-11-08  Brazil      665.0        33.0    unknown
49  2024-11-10  Brazil      405.0        20.0    unknown
73  2024-11-14  Brazil      718.0        35.0    unknown
74  2024-11-15  Brazil      728.0        36.0    unknown
110 2024-11-21  Brazil     1248.0        62.0    unknown
132 2024-11-25  Brazil     1063.0        53.0    unknown
134 2024-11-25  Brazil      357.0        17.0    unknown
158 2024-11-30  Brazil     1619.0        80.0    unknown
160 2024-11-30  Brazil      514.0        25.0    unknown
163 2024-11-30  Brazil        0.0         0.0    unknown

In [103]:
# checking columns with unknown values

column_brazil = df[df['country'] == 'Brazil']

column_brazil.head(50)

         date country  new_cases  new_deaths vaccinated
1  2024-11-01  Brazil        0.0         0.0        327
3  2024-11-01  Brazil      971.0        48.0        430
4  2024-11-01  Brazil      176.0         8.0    unknown
5  2024-11-01  Brazil     1034.0        51.0        462
6  2024-11-02  Brazil       23.0         1.0        195
8  2024-11-02  Brazil      185.0         9.0        173
9  2024-11-02  Brazil      615.0        30.0        369
10 2024-11-02  Brazil      376.0        18.0         61
11 2024-11-03  Brazil      337.0        16.0        425
13 2024-11-03  Brazil      641.0         NaN         47
14 2024-11-03  Brazil      785.0        39.0        320
15 2024-11-03  Brazil       35.0         1.0        369
16 2024-11-04  Brazil       96.0         4.0        383
17 2024-11-04  Brazil        0.0         0.0        440
18 2024-11-04  Brazil      793.0        39.0        137
20 2024-11-04  Brazil      884.0        44.0        493
21 2024-11-04  Brazil      696.0        34.0    unknown
22 2024-11-05  Brazil      283.0         NaN         41
23 2024-11-05  Brazil      140.0         7.0        450
24 2024-11-05  Brazil      638.0        31.0        346
25 2024-05-11  Brazil      867.0        43.0        485
26 2024-11-05  Brazil      772.0        38.0        359
27 2024-11-06  Brazil      377.0        18.0        418
28 2024-11-06  Brazil      351.0        17.0        401
29 2024-11-06  Brazil       10.0         0.0          2
30 2024-11-06  Brazil      152.0         NaN        421
31 2024-11-06  Brazil      483.0        24.0        383
32 2024-11-07  Brazil      391.0        19.0         75
33 2024-11-07  Brazil      423.0        21.0        339
34 2024-11-07  Brazil      605.0        30.0        121
35 2024-07-11  Brazil      560.0        28.0        449
36 2024-11-07  Brazil        0.0         0.0        115
37 2024-11-08  Brazil      665.0        33.0    unknown
38 2024-11-08  Brazil      313.0        15.0        486
40 2024-11-08  Brazil      212.0         NaN        313
41 2024-11-08  Brazil      404.0        20.0        484
42 2024-11-08  Brazil      444.0        22.0        276
43 2024-11-09  Brazil      376.0        18.0        174
44 2024-11-09  Brazil      268.0        13.0        358
45 2024-11-09  Brazil      918.0        45.0         57
46 2024-11-09  Brazil      320.0        16.0        476
47 2024-11-09  Brazil      853.0        42.0        252
48 2024-11-10  Brazil      454.0        22.0        142
49 2024-11-10  Brazil      405.0        20.0    unknown
50 2024-11-10  Brazil       57.0         2.0         18
51 2024-11-10  Brazil      209.0        10.0        418
52 2024-11-10  Brazil        0.0         0.0        171
53 2024-11-11  Brazil      532.0        26.0        378
54 2024-11-11  Brazil      403.0        20.0        454
56 2024-11-11  Brazil        0.0         0.0        471

In [104]:
# viewing last 50 row to observe how to handle the missing data
df.tail(50)

          date country  new_cases  new_deaths vaccinated
103 2024-11-20  Brazil      589.0        29.0        120
105 2024-11-20  Brazil      749.0        37.0        421
106 2024-11-20  Brazil      587.0        29.0         11
110 2024-11-21  Brazil     1248.0        62.0    unknown
111 2024-11-21  Brazil      626.0        31.0        499
112 2024-11-21  Brazil      896.0        44.0        187
113 2024-11-21  Brazil      606.0        30.0        465
114 2024-11-21  Brazil      588.0        29.0        107
115 2024-11-22  Brazil      896.0         NaN        349
116 2024-11-22  Brazil      741.0        37.0        346
117 2024-11-22  Brazil      345.0        17.0        397
119 2024-11-22  Brazil      664.0        33.0        309
120 2024-11-22  Brazil      627.0        31.0        278
121 2024-11-23  Brazil     1196.0        59.0        422
122 2024-11-23  Brazil     1087.0        54.0        395
124 2024-11-23  Brazil      151.0         7.0        131
125 2024-11-23  Brazil      730.0        36.0        427
126 2024-11-23  Brazil     1030.0        51.0         30
127 2024-11-24  Brazil      831.0        41.0         33
128 2024-11-24  Brazil     1196.0        59.0        356
129 2024-11-24  Brazil       66.0         3.0        498
130 2024-11-24  Brazil      597.0         NaN        319
131 2024-11-24  Brazil       10.0         0.0        375
132 2024-11-25  Brazil     1063.0        53.0    unknown
134 2024-11-25  Brazil      357.0        17.0    unknown
135 2024-11-25  Brazil       48.0         2.0        377
136 2024-11-25  Brazil     1093.0        54.0        266
137 2024-11-26  Brazil     1350.0        67.0        175
138 2024-11-26  Brazil     1568.0        78.0        496
139 2024-11-26  Brazil      410.0        20.0         70
140 2024-11-26  Brazil      778.0        38.0        440
141 2024-11-26  Brazil      949.0        47.0        444
142 2024-11-27  Brazil     1470.0        73.0        233
143 2024-11-27  Brazil     1074.0         NaN        446
144 2024-11-27  Brazil      759.0        37.0        418
146 2024-11-27  Brazil      521.0        26.0         17
147 2024-11-28  Brazil     1228.0        61.0        171
148 2024-11-28  Brazil     1730.0        86.0        347
149 2024-11-28  Brazil      141.0         7.0        134
150 2024-11-28  Brazil      803.0         NaN        483
151 2024-11-28  Brazil      401.0        20.0        190
153 2024-11-29  Brazil     1661.0        83.0        220
154 2024-11-29  Brazil     1650.0        82.0        491
156 2024-11-29  Brazil      618.0        30.0        351
157 2024-11-29  Brazil       67.0         3.0        490
158 2024-11-30  Brazil     1619.0        80.0    unknown
159 2024-11-30  Brazil     1473.0        73.0        428
160 2024-11-30  Brazil      514.0        25.0    unknown
161 2024-11-30  Brazil     1133.0        56.0        438
163 2024-11-30  Brazil        0.0         0.0    unknown

In [113]:
# selecting columns with number data types

df_num = df.select_dtypes(include=['number'])

# new_df1 = df

In [116]:
# using iterative imputer to handle missing values

from sklearn.experimental import enable_iterative_imputer as eii

from sklearn.impute import IterativeImputer as ii


iterate = ii()

df_iterate = pd.DataFrame(iterate.fit_transform(df_num), columns=df_num.columns, index=df_num.index)

In [128]:
# Applying the transformed data to a copy of df

df_imputed = df.copy()

df_imputed

df_imputed[df_num.columns] = df_iterate

df_imputed.head(20)

         date country  new_cases  new_deaths vaccinated
1  2024-11-01  Brazil        0.0    0.000000        327
3  2024-11-01  Brazil      971.0   48.000000        430
4  2024-11-01  Brazil      176.0    8.000000    unknown
5  2024-11-01  Brazil     1034.0   51.000000        462
6  2024-11-02  Brazil       23.0    1.000000        195
8  2024-11-02  Brazil      185.0    9.000000        173
9  2024-11-02  Brazil      615.0   30.000000        369
10 2024-11-02  Brazil      376.0   18.000000         61
11 2024-11-03  Brazil      337.0   16.000000        425
13 2024-11-03  Brazil      641.0   31.585458         47
14 2024-11-03  Brazil      785.0   39.000000        320
15 2024-11-03  Brazil       35.0    1.000000        369
16 2024-11-04  Brazil       96.0    4.000000        383
17 2024-11-04  Brazil        0.0    0.000000        440
18 2024-11-04  Brazil      793.0   39.000000        137
20 2024-11-04  Brazil      884.0   44.000000        493
21 2024-11-04  Brazil      696.0   34.000000    unknown
22 2024-11-05  Brazil      283.0   13.729814         41
23 2024-11-05  Brazil      140.0    7.000000        450
24 2024-11-05  Brazil      638.0   31.000000        346

In [127]:
df_iterate.head(20)

    new_cases  new_deaths
1         0.0    0.000000
3       971.0   48.000000
4       176.0    8.000000
5      1034.0   51.000000
6        23.0    1.000000
8       185.0    9.000000
9       615.0   30.000000
10      376.0   18.000000
11      337.0   16.000000
13      641.0   31.585458
14      785.0   39.000000
15       35.0    1.000000
16       96.0    4.000000
17        0.0    0.000000
18      793.0   39.000000
20      884.0   44.000000
21      696.0   34.000000
22      283.0   13.729814
23      140.0    7.000000
24      638.0   31.000000