In [20]:
# Importing required module

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
# importing the dataset
df = pd.read_csv('covid_19_Dataset.csv')

df

          DATE    country    NEW Cases  NEW_DEATHS vaccinated
0    2024-11-01  Argentina         NaN         NaN     unknown
1    2024-11-01  Australia         0.0         0.0         327
2    2024-11-01  Australia         0.0         0.0         327
3    2024-11-01     Brazil       971.0        48.0         430
4    2024-11-01     Canada       176.0         8.0     unknown
..          ...        ...         ...         ...         ...
160  2024-11-30     Brazil       514.0        25.0     unknown
161  2024-11-30     Canada      1133.0        56.0         438
162  2024-11-30     Canada      1133.0        56.0         438
163  2024-11-30      China         0.0         0.0     unknown
164  2024-11-30      China         0.0         0.0     unknown

[165 rows x 5 columns]

In [22]:
# checking the data information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE         165 non-null    object
 1   country      165 non-null    object
 2    NEW Cases   154 non-null    float64
 3   NEW_DEATHS   139 non-null    float64
 4   vaccinated   165 non-null    object
dtypes: float64(2), object(3)
memory usage: 6.6+ KB

In [23]:
# checking the data information

df.shape

(165, 5)

In [24]:
# Renaming coumns
df.rename(columns={'NEW Cases': 'new_cases', 'NEW_DEATHS': 'new_deaths', 'DATE': 'date'}, inplace=True)

df

          DATE    country    NEW Cases  new_deaths vaccinated
0    2024-11-01  Argentina         NaN         NaN     unknown
1    2024-11-01  Australia         0.0         0.0         327
2    2024-11-01  Australia         0.0         0.0         327
3    2024-11-01     Brazil       971.0        48.0         430
4    2024-11-01     Canada       176.0         8.0     unknown
..          ...        ...         ...         ...         ...
160  2024-11-30     Brazil       514.0        25.0     unknown
161  2024-11-30     Canada      1133.0        56.0         438
162  2024-11-30     Canada      1133.0        56.0         438
163  2024-11-30      China         0.0         0.0     unknown
164  2024-11-30      China         0.0         0.0     unknown

[165 rows x 5 columns]

In [25]:
# Strip leading and trailing spaces from column names
df.columns = df.columns.str.strip().str.lower()

df

           date    country  new cases  new_deaths vaccinated
0    2024-11-01  Argentina        NaN         NaN    unknown
1    2024-11-01  Australia        0.0         0.0        327
2    2024-11-01  Australia        0.0         0.0        327
3    2024-11-01     Brazil      971.0        48.0        430
4    2024-11-01     Canada      176.0         8.0    unknown
..          ...        ...        ...         ...        ...
160  2024-11-30     Brazil      514.0        25.0    unknown
161  2024-11-30     Canada     1133.0        56.0        438
162  2024-11-30     Canada     1133.0        56.0        438
163  2024-11-30      China        0.0         0.0    unknown
164  2024-11-30      China        0.0         0.0    unknown

[165 rows x 5 columns]

In [ ]:
# Renaming coumns again


df.rename(columns={'new cases': 'new_cases'}, inplace=True)

df

           date    country  new_cases  new_deaths vaccinated
0    2024-11-01  Argentina        NaN         NaN    unknown
1    2024-11-01  Australia        0.0         0.0        327
2    2024-11-01  Australia        0.0         0.0        327
3    2024-11-01     Brazil      971.0        48.0        430
4    2024-11-01     Canada      176.0         8.0    unknown
..          ...        ...        ...         ...        ...
160  2024-11-30     Brazil      514.0        25.0    unknown
161  2024-11-30     Canada     1133.0        56.0        438
162  2024-11-30     Canada     1133.0        56.0        438
163  2024-11-30      China        0.0         0.0    unknown
164  2024-11-30      China        0.0         0.0    unknown

[165 rows x 5 columns]

In [ ]:
# Converting Date column data type

df['date'] = pd.to_datetime(df['date'], format='mixed', dayfirst=True)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        165 non-null    datetime64[ns]
 1   country     165 non-null    object
 2   new_cases   154 non-null    float64
 3   new_deaths  139 non-null    float64
 4   vaccinated  165 non-null    object
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 6.6+ KB

In [38]:
# viewing data

df

          date    country  new_cases  new_deaths vaccinated
0   2024-11-01  Argentina        NaN         NaN    unknown
1   2024-11-01  Australia        0.0         0.0        327
2   2024-11-01  Australia        0.0         0.0        327
3   2024-11-01     Brazil      971.0        48.0        430
4   2024-11-01     Canada      176.0         8.0    unknown
..         ...        ...        ...         ...        ...
160 2024-11-30     Brazil      514.0        25.0    unknown
161 2024-11-30     Canada     1133.0        56.0        438
162 2024-11-30     Canada     1133.0        56.0        438
163 2024-11-30      China        0.0         0.0    unknown
164 2024-11-30      China        0.0         0.0    unknown

[165 rows x 5 columns]

In [ ]:
# Checking columns with null values

df.isnull().sum()

date           0
country        0
new_cases     11
new_deaths    26
vaccinated     0
dtype: int64